import { SearchResult } from '@/components/ui/search-with-results'

// Mock search function for demonstration
export async function mockSearchAPI(query: string): Promise<{ results: SearchResult[], total: number }> {
    // Simulate API delay
    await new Promise(resolve => setTimeout(resolve, 500))

    const allResults: SearchResult[] = [
        // Yacht activities
        {
            id: '1',
            name: 'Прогулка на яхте по Дубровнику',
            type: 'activity',
            category: 'water-sports',
            location: 'Дубровник',
            price: 150,
            image: 'https://images.unsplash.com/photo-1567899378494-47b22a2ae96a?w=400&q=80',
        },
        {
            id: '11',
            name: 'Яхтинг в Элафитских островах',
            type: 'activity',
            category: 'water-sports',
            location: 'Дубровник',
            price: 180,
            image: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=400&q=80',
        },
        {
            id: '12',
            name: 'Аренда яхты на полдня',
            type: 'activity',
            category: 'water-sports',
            location: 'Сплит',
            price: 220,
            image: 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=400&q=80',
        },
        {
            id: '13',
            name: 'Яхтинг с рыбалкой',
            type: 'activity',
            category: 'yacht-fishing',
            location: 'Хвар',
            price: 250,
            image: 'https://images.unsplash.com/photo-1544551763-77ef2d0cfc6c?w=400&q=80',
        },
        {
            id: '14',
            name: 'Романтическая яхт-прогулка на закате',
            type: 'activity',
            category: 'water-sports',
            location: 'Ровинь',
            price: 190,
            image: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=400&q=80',
        },
        {
            id: '15',
            name: 'Яхтенный тур по островам',
            type: 'activity',
            category: 'water-sports',
            location: 'Корнати',
            price: 280,
            image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=400&q=80',
        },
        {
            id: '16',
            name: 'Приватная яхта VIP класса',
            type: 'activity',
            category: 'water-sports',
            location: 'Дубровник',
            price: 450,
            image: 'https://images.unsplash.com/photo-1567899378494-47b22a2ae96a?w=400&q=80',
        },
        {
            id: '26',
            name: 'Яхта для корпоратива',
            type: 'activity',
            category: 'water-sports',
            location: 'Сплит',
            price: 350,
            image: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=400&q=80',
        },
        {
            id: '27',
            name: 'Яхтенная рыбалка на целый день',
            type: 'activity',
            category: 'yacht-fishing',
            location: 'Макарска',
            price: 320,
            image: 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=400&q=80',
        },
        {
            id: '28',
            name: 'Свадебная прогулка на яхте',
            type: 'activity',
            category: 'water-sports',
            location: 'Дубровник',
            price: 580,
            image: 'https://images.unsplash.com/photo-1567899378494-47b22a2ae96a?w=400&q=80',
        },
        {
            id: '29',
            name: 'Яхтенное путешествие к острову Млет',
            type: 'activity',
            category: 'water-sports',
            location: 'Млет',
            price: 240,
            image: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=400&q=80',
        },

        // Other activities and places
        {
            id: '2',
            name: 'Ресторан La Vista',
            type: 'place',
            category: 'gastronomy',
            location: 'Сплит',
            image: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=400&q=80',
        },
        {
            id: '3',
            name: 'Дайвинг на рифах',
            type: 'activity',
            category: 'water-sports',
            location: 'Хвар',
            price: 80,
            image: 'https://images.unsplash.com/photo-1544551763-77ef2d0cfc6c?w=400&q=80',
        },
        {
            id: '4',
            name: 'SPA центр Relaxation',
            type: 'place',
            category: 'wellness-spa',
            location: 'Опатия',
            image: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=400&q=80',
        },
        {
            id: '5',
            name: 'Тур по винодельням',
            type: 'activity',
            category: 'food-tours',
            location: 'Истрия',
            price: 120,
            image: 'https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?w=400&q=80',
        },
        {
            id: '17',
            name: 'Винный тур в Пелешац',
            type: 'activity',
            category: 'food-tours',
            location: 'Пелешац',
            price: 95,
            image: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=400&q=80',
        },
        {
            id: '18',
            name: 'Дегустация вин Истрии',
            type: 'activity',
            category: 'food-tours',
            location: 'Мотовун',
            price: 85,
            image: 'https://images.unsplash.com/photo-1547595628-c61a29f496f0?w=400&q=80',
        },
        {
            id: '6',
            name: 'Парашютинг над Адриатикой',
            type: 'activity',
            category: 'extreme-sports',
            location: 'Дубровник',
            price: 200,
            image: 'https://images.unsplash.com/photo-1583212292454-1fe6229603b7?w=400&q=80',
        },
        {
            id: '7',
            name: 'Пляж Златни Рат',
            type: 'place',
            category: 'nature',
            location: 'Брач',
            image: 'https://images.unsplash.com/photo-1519046904884-53103b34b206?w=400&q=80',
        },
        {
            id: '19',
            name: 'Пляж Бачвице',
            type: 'place',
            category: 'nature',
            location: 'Сплит',
            image: 'https://images.unsplash.com/photo-1519046904884-53103b34b206?w=400&q=80',
        },
        {
            id: '20',
            name: 'Пляж Сунь',
            type: 'place',
            category: 'nature',
            location: 'Лопуд',
            image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=400&q=80',
        },
        {
            id: '8',
            name: 'Фотосессия на закате',
            type: 'activity',
            category: 'photoshoots',
            location: 'Ровинь',
            price: 90,
            image: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=400&q=80',
        },
        {
            id: '9',
            name: 'Музей Галереи Меринг',
            type: 'place',
            category: 'culture',
            location: 'Загреб',
            image: 'https://images.unsplash.com/photo-1564399579883-451a5d44ec08?w=400&q=80',
        },
        {
            id: '10',
            name: 'Каякинг у Корнати',
            type: 'activity',
            category: 'water-sports',
            location: 'Задар',
            price: 75,
            image: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=400&q=80',
        },
        {
            id: '21',
            name: 'Дайвинг для начинающих',
            type: 'activity',
            category: 'water-sports',
            location: 'Корчула',
            price: 65,
            image: 'https://images.unsplash.com/photo-1544551763-77ef2d0cfc6c?w=400&q=80',
        },
        {
            id: '22',
            name: 'SPA в отеле Grand',
            type: 'place',
            category: 'wellness-spa',
            location: 'Дубровник',
            image: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=400&q=80',
        },
        {
            id: '23',
            name: 'Массаж и релаксация',
            type: 'place',
            category: 'wellness-spa',
            location: 'Хвар',
            price: 70,
            image: 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=400&q=80',
        },
        {
            id: '24',
            name: 'Тур по Старому городу',
            type: 'activity',
            category: 'cultural-tours',
            location: 'Дубровник',
            price: 45,
            image: 'https://images.unsplash.com/photo-1555990538-c3ec17616457?w=400&q=80',
        },
        {
            id: '25',
            name: 'Экскурсия в Трстено',
            type: 'activity',
            category: 'cultural-tours',
            location: 'Трстено',
            price: 55,
            image: 'https://images.unsplash.com/photo-1564399579883-451a5d44ec08?w=400&q=80',
        },
    ]

    // Simple search filter - search in name, location, and category
    const filtered = query.trim()
        ? allResults.filter(r =>
            r.name.toLowerCase().includes(query.toLowerCase()) ||
            r.location?.toLowerCase().includes(query.toLowerCase()) ||
            r.category?.toLowerCase().includes(query.toLowerCase())
        )
        : allResults

    return {
        results: filtered,
        total: filtered.length,
    }
}